import React from "react";

const data = [
    {
        id:1,
        name: "2024 Porsche 911 GT3Rs",
        brand: "Porsche",
        model: "911 GT3Rs",
        color: "white",
        year: 2024,
        mileage: 4000,
        price: 300000,
        bodyType: "Coupe",
        doors: 2,
        engine: "4.0-liter naturally aspirated flat-six",
        transmission: "7-speed dual-clutch automatic",
        fuel: "Gasoline",
        driveTrain: "Rear Wheel Drive (RWD)",
        bannerPic: "./CarDetails/GT3_Rs/Porsche_911_GT3Rs.png",
        detailPic: ["./CarDetails/GT3_Rs/p1.jpg","./CarDetails/GT3_Rs/p2.jpg","./CarDetails/GT3_Rs/p3.jpg","./CarDetails/GT3_Rs/p4.jpg","./CarDetails/GT3_Rs/p5.jpg","./CarDetails/GT3_Rs/p6.jpg","./CarDetails/GT3_Rs/p7.jpg","./CarDetails/GT3_Rs/p8.jpg"],
    },
    {
        id:2,
        name: "2017 Ferrari 488 Spider",
        brand: "Ferrari",
        model: "488 Spider",
        color: "white",
        year: 2017,
        mileage: 1000,
        price: 296524,
        bodyType: "Convertible",
        doors: 2,
        engine: "3.9-liter twin-turbocharged V8",
        transmission: "7-speed dual-clutch automatic",
        fuel: "Gasoline",
        driveTrain: "Rear Wheel Drive (RWD)",
        bannerPic: "./CarDetails/Ferrari 488 Spider/Ferrari488Spider.jpg",
        detailPic: ["./CarDetails/Ferrari 488 Spider/p1.jpg","./CarDetails/Ferrari 488 Spider/p2.jpg","./CarDetails/Ferrari 488 Spider/p3.jpg","./CarDetails/Ferrari 488 Spider/p4.jpg","./CarDetails/Ferrari 488 Spider/p5.jpg","./CarDetails/Ferrari 488 Spider/p6.jpg","./CarDetails/Ferrari 488 Spider/p7.jpg","./CarDetails/Ferrari 488 Spider/p8.jpg"],
    },
    {
        id:3,
        name: "2019 Lamborghini Sián FKP 37",
        brand: "Lamborghini",
        model: "Sián FKP 37",
        color: "green",
        year: 2019,
        mileage: 2000,
        price: 3699900,
        bodyType: "Coupe",
        doors: 2,
        engine: "6.5-liter naturally aspirated V12 engine paired with a 48-volt mild-hybrid system",
        transmission: "7-speed Independent Shifting Rod",
        fuel: "semi-Hybrid",
        driveTrain: "All Wheel Drive (AWD)",
        bannerPic: "./CarDetails/LamborghiniSianFKP37/Lamborghini.jpg",
        detailPic: ["./CarDetails/LamborghiniSianFKP37/p1.jpg","./CarDetails/LamborghiniSianFKP37/p2.jpg","./CarDetails/LamborghiniSianFKP37/p3.jpg","./CarDetails/LamborghiniSianFKP37/p4.jpg","./CarDetails/LamborghiniSianFKP37/p5.jpg","./CarDetails/LamborghiniSianFKP37/p6.jpg","./CarDetails/LamborghiniSianFKP37/p7.jpg","./CarDetails/LamborghiniSianFKP37/p8.jpg",],
    },
    {
        id:4,
        name: "2017 Mini Cooper S R56",
        brand: "Mini Cooper",
        model: "Mini Copper S R56",
        color: "red",
        year: 2017,
        mileage: 10000,
        price: 21400,
        bodyType: "Hatchback",
        doors: 3,
        engine: " 1.6-liter turbocharged I-4",
        transmission: "6-speed manual",
        fuel: "Gasoline",
        driveTrain: "Front Wheel Drive (FWD)",
        bannerPic: "./CarDetails/2017 Mini Cooper S R56/MiniCooper.jpg",
        detailPic: ["./CarDetails/2017 Mini Cooper S R56/p1.jpg","./CarDetails/2017 Mini Cooper S R56/p2.jpg","./CarDetails/2017 Mini Cooper S R56/p3.jpg","./CarDetails/2017 Mini Cooper S R56/p4.jpg",],
    },
    {
        id:5,
        name: "2019 Mercedes-AMG G63",
        brand: "Mercedes",
        model: "G63",
        color: "white",
        year: 2019,
        mileage: 1590,
        price: 190000,
        bodyType: "SUV",
        doors: 4,
        engine: " 4.0-liter V8 twin-turbocharged",
        transmission: "9-speed automatic transmission (AMG Speedshift TCT)",
        fuel: "Gasoline",
        driveTrain: "All Wheel Drive (AWD)",
        bannerPic: "./CarDetails/G63AMG/MercedesG63.jpg",
        detailPic: ["./CarDetails/G63AMG/p1.jpg","./CarDetails/G63AMG/p2.jpg","./CarDetails/G63AMG/p3.jpg","./CarDetails/G63AMG/p4.jpg","./CarDetails/G63AMG/p5.jpg","./CarDetails/G63AMG/p6.jpg","./CarDetails/G63AMG/p7.jpg","./CarDetails/G63AMG/p8.jpg",],
    },
    {
        id:6,
        name: "2020 Audi R8 Convertible",
        brand: "Audi",
        model: "R8",
        color: "blue",
        year: 2020,
        mileage: 3590,
        price: 175000,
        bodyType: "Convertible",
        doors: 2,
        engine: "5.2-liter V10",
        transmission: "7-speed dual-clutch automatic (S tronic)",
        fuel: "Gasoline",
        driveTrain: "All Wheel Drive (AWD)",
        bannerPic: "./CarDetails/AudiR8/AudiR8.jpg",
        detailPic: ["./CarDetails/AudiR8/p1.jpg","./CarDetails/AudiR8/p2.jpg","./CarDetails/AudiR8/p3.jpg","./CarDetails/AudiR8/p4.jpg","./CarDetails/AudiR8/p5.jpg","./CarDetails/AudiR8/p6.jpg","./CarDetails/AudiR8/p7.jpg","./CarDetails/AudiR8/p8.jpg",],
    },
    {
        id:7,
        name: "2020 Dodge Challenger SRT",
        brand: "Dodge",
        model: "Challenger SRT, Hellcat",
        color: "red",
        year: 2020,
        mileage: 15000,
        price: 70000,
        bodyType: "Coupe",
        doors: 2,
        engine: "6.2L Supercharged HEMI® V8",
        transmission: "8-Speed Automatic",
        fuel: "Gasoline",
        driveTrain: "Rear Wheel Drive (RWD)",
        bannerPic: "./CarDetails/DodgeChallenger/DodgeHellcat.jpg",
        detailPic: ["./CarDetails/DodgeChallenger/p1.jpg","./CarDetails/DodgeChallenger/p2.jpg","./CarDetails/DodgeChallenger/p3.jpg","./CarDetails/DodgeChallenger/p4.jpg","./CarDetails/DodgeChallenger/p5.jpg","./CarDetails/DodgeChallenger/p6.jpg","./CarDetails/DodgeChallenger/p7.jpg","./CarDetails/DodgeChallenger/p8.jpg",],
    },
    {
        id:8,
        name: "2019 Subaru WRX STI",
        brand: "Subaru",
        model: "WRX STI",
        color: "white",
        year: 2019,
        mileage: 5600,
        price: 38500,
        bodyType: "Sedan",
        doors: 4,
        engine: " 2.5L 4-cylinder Boxer engine",
        transmission: " 6-speed manual",
        fuel: "Gasoline",
        driveTrain: "All Wheel Drive (AWD)",
        bannerPic: "./CarDetails/SubaruWRXSTI/SubaruWRXSTI.jpg",
        detailPic: ["./CarDetails/SubaruWRXSTI/p1.jpg","./CarDetails/SubaruWRXSTI/p2.jpg","./CarDetails/SubaruWRXSTI/p3.jpg","./CarDetails/SubaruWRXSTI/p4.jpg","./CarDetails/SubaruWRXSTI/p5.jpg","./CarDetails/SubaruWRXSTI/p6.jpg","./CarDetails/SubaruWRXSTI/p7.jpg","./CarDetails/SubaruWRXSTI/p8.jpg",],
    },
    {
        id:9,
        name: "2024 Aston Martin Valkyrie",
        brand: "Aston Martin",
        model: "Valkyrie",
        color: "green",
        year: 2024,
        mileage: 300,
        price: 3500000,
        bodyType: "Convertible",
        doors: 2,
        engine: " 6.5-liter V12",
        transmission: " 7-speed paddle-shift transmission",
        fuel: "Hybrid",
        driveTrain: "Rear Wheel Drive (RWD)",
        bannerPic: "./CarDetails/AstonMartinValkyrie/AstonMartinValkyrie.jpg",
        detailPic: ["./CarDetails/AstonMartinValkyrie/p1.jpg","./CarDetails/AstonMartinValkyrie/p2.jpg","./CarDetails/AstonMartinValkyrie/p3.jpg","./CarDetails/AstonMartinValkyrie/p4.jpg",],
    },
    {
        id:10,
        name: "2023 Bentley Bentayga",
        brand: "Bentley",
        model: "Bentayga",
        color: "blue",
        year: 2023,
        mileage: 1320,
        price: 201000,
        bodyType: "SUV",
        doors: 4,
        engine: "4.0L V8 twin-turbocharged",
        transmission: "8-speed automatic with overdrive",
        fuel: "Gasoline",
        driveTrain: "All Wheel Drive (AWD)",
        bannerPic: "./CarDetails/BentleyBentayga/BentleyBentayga.jpg",
        detailPic: ["./CarDetails/BentleyBentayga/p1.jpg","./CarDetails/BentleyBentayga/p2.jpg","./CarDetails/BentleyBentayga/p3.jpg","./CarDetails/BentleyBentayga/p4.jpg","./CarDetails/BentleyBentayga/p5.jpg","./CarDetails/BentleyBentayga/p6.jpg",],
    },
    {
        id:11,
        name: "2024 BMW M3",
        brand: "BMW",
        model: "M3",
        color: "green",
        year: 2024,
        mileage: 340,
        price: 78000,
        bodyType: "Sedan",
        doors: 4,
        engine: "3.0-liter inline-6 engine",
        transmission: "6-speed manual",
        fuel: "Gasoline",
        driveTrain: "Rear Wheel Drive (RWD)",
        bannerPic: "./CarDetails/BMWM3/BMWM3.jpg",
        detailPic: ["./CarDetails/BMWM3/p1.jpg","./CarDetails/BMWM3/p2.jpg","./CarDetails/BMWM3/p3.jpg","./CarDetails/BMWM3/p4.jpg","./CarDetails/BMWM3/p5.jpg","./CarDetails/BMWM3/p6.jpg",],
    },
    {
        id:12,
        name: "2019 BMW X5",
        brand: "BMW",
        model: "X5",
        color: "white",
        year: 2019,
        mileage: 1430,
        price: 62500,
        bodyType: "SAV",
        doors: 5,
        engine: "2.0L inline-4 turbocharged",
        transmission: "8-speed automatic (Steptronic)",
        fuel: "Gasoline",
        driveTrain: "All Wheel Drive (AWD)",
        bannerPic: "./CarDetails/BMWX5/BMWX5.jpg",
        detailPic: ["./CarDetails/BMWX5/p1.jpg","./CarDetails/BMWX5/p2.jpg","./CarDetails/BMWX5/p3.jpg","./CarDetails/BMWX5/p4.jpg","./CarDetails/BMWX5/p5.jpg","./CarDetails/BMWX5/p6.jpg","./CarDetails/BMWX5/p7.jpg","./CarDetails/BMWX5/p8.jpg",],
    },
    {
        id:13,
        name: "2021 Cadillac Escalade ESV Sport Platinum",
        brand: "Cadillac",
        model: "Escalade",
        color: "black",
        year: 2021,
        mileage: 2400,
        price: 80000,
        bodyType: "SUV",
        doors: 4,
        engine: "6.2-liter V8",
        transmission: "10-speed automatic",
        fuel: "Gasoline",
        driveTrain: "Rear Wheel Drive (RWD), 4 Wheel Drive (4WD)",
        bannerPic: "./CarDetails/CadillacEscalade/CadillacEscalade.jpg",
        detailPic: ["./CarDetails/CadillacEscalade/p1.jpg","./CarDetails/CadillacEscalade/p2.jpg","./CarDetails/CadillacEscalade/p3.jpg","./CarDetails/CadillacEscalade/p4.jpg","./CarDetails/CadillacEscalade/p5.jpg","./CarDetails/CadillacEscalade/p6.jpg","./CarDetails/CadillacEscalade/p7.jpg","./CarDetails/CadillacEscalade/p8.jpg",],
    },
    {
        id:14,
        name: "2020 Chevrolet Corvette Stingray",
        brand: "Chevrolet",
        model: "Corvette Stingray",
        color: "red",
        year: 2020,
        mileage: 3400,
        price: 69000,
        bodyType: "Convertible",
        doors: 2,
        engine: "6.2-liter V8 ",
        transmission: "8-speed dual-clutch automatic",
        fuel: "Gasoline",
        driveTrain: "Rear Wheel Drive (RWD)",
        bannerPic: "./CarDetails/ChevroletCorvette/ChevroletCorvette.jpg",
        detailPic: ["./CarDetails/ChevroletCorvette/p1.jpg","./CarDetails/ChevroletCorvette/p2.jpg","./CarDetails/ChevroletCorvette/p3.jpg","./CarDetails/ChevroletCorvette/p4.jpg","./CarDetails/ChevroletCorvette/p5.jpg","./CarDetails/ChevroletCorvette/p6.jpg","./CarDetails/ChevroletCorvette/p7.jpg","./CarDetails/ChevroletCorvette/p8.jpg",],
    },
    {
        id:15,
        name: "2018 Ford F-150 Raptor",
        brand: "Ford",
        model: "F150 Raptor",
        color: "black",
        year: 2018,
        mileage: 40000,
        price: 43000,
        bodyType: "Pickup Truck",
        doors: 4,
        engine: "3.5L V6 EcoBoost",
        transmission: "10-speed automatic",
        fuel: "Gasoline",
        driveTrain: "4 Wheel Drive (4WD)",
        bannerPic: "./CarDetails/FordF150Raptor/FordF150Raptor.jpg",
        detailPic: ["./CarDetails/FordF150Raptor/p1.jpg","./CarDetails/FordF150Raptor/p2.jpg","./CarDetails/FordF150Raptor/p3.jpg","./CarDetails/FordF150Raptor/p4.jpg","./CarDetails/FordF150Raptor/p5.jpg","./CarDetails/FordF150Raptor/p6.jpg","./CarDetails/FordF150Raptor/p7.jpg","./CarDetails/FordF150Raptor/p8.jpg",],
    },
    {
        id:16,
        name: " 2017 GMC Canyon",
        brand: "GMC",
        model: "Canyon",
        color: "black",
        year: 2017,
        mileage: 29000,
        price: 18000,
        bodyType: "Pickup Truck",
        doors: 4,
        engine: "3.6L V6",
        transmission: "6-speed automatic",
        fuel: "Gasoline",
        driveTrain: "4 Wheel Drive (4WD)",
        bannerPic: "./CarDetails/GMCCanyon/GMCCanyon.jpg",
        detailPic: ["./CarDetails/GMCCanyon/p1.jpg","./CarDetails/GMCCanyon/p2.jpg","./CarDetails/GMCCanyon/p3.jpg","./CarDetails/GMCCanyon/p4.jpg","./CarDetails/GMCCanyon/p5.jpg","./CarDetails/GMCCanyon/p6.jpg","./CarDetails/GMCCanyon/p7.jpg","./CarDetails/GMCCanyon/p8.jpg",],
    },
    {
        id:17,
        name: "2018 Honda Civic Type R",
        brand: "Honda",
        model: "Civic",
        color: "blue",
        year: 2018,
        mileage: 12000,
        price: 29000,
        bodyType: "Hatchback",
        doors: 4,
        engine: "2.0L inline-4 turbocharged",
        transmission: "6-speed manual",
        fuel: "Premium Gasoline",
        driveTrain: "Front Wheel Drive (FWD)",
        bannerPic: "./CarDetails/HondaCivicTypeR/HondaCivicTypeR.jpg",
        detailPic: ["./CarDetails/HondaCivicTypeR/p1.jpg","./CarDetails/HondaCivicTypeR/p2.jpg","./CarDetails/HondaCivicTypeR/p3.jpg","./CarDetails/HondaCivicTypeR/p4.jpg","./CarDetails/HondaCivicTypeR/p5.jpg","./CarDetails/HondaCivicTypeR/p6.jpg","./CarDetails/HondaCivicTypeR/p7.jpg","./CarDetails/HondaCivicTypeR/p8.jpg",],
    },
    {
        id:18,
        name: "2018 Hyundai Accent Manual",
        brand: "Hyundai",
        model: "Accent",
        color: "white",
        year: 2018,
        mileage: 24500,
        price: 10900,
        bodyType: "Sedan",
        doors: 4,
        engine: "2.0L I4",
        transmission: "6-speed manual",
        driveTrain: "Front Wheel Drive (FWD)",
        bannerPic: "./CarDetails/HyundaiAccent/HyundaiAccent.jpg",
        detailPic: ["./CarDetails/HyundaiAccent/p1.jpg","./CarDetails/HyundaiAccent/p2.jpg","./CarDetails/HyundaiAccent/p3.jpg","./CarDetails/HyundaiAccent/p4.jpg","./CarDetails/HyundaiAccent/p5.jpg","./CarDetails/HyundaiAccent/p6.jpg","./CarDetails/HyundaiAccent/p7.jpg","./CarDetails/HyundaiAccent/p8.jpg",],
    },
    {
        id:19,
        name: "2022 Jaguar F-Type",
        brand: "Jaguar",
        model: "F-Type",
        color: "white",
        year: 2022,
        mileage: 2340,
        price: 72000,
        bodyType: "Convertible",
        doors: 2,
        engine: "5.0L V8",
        transmission: "8-speed automatic",
        fuel: "Gasoline",
        driveTrain: "Rear Wheel Drive (RWD)",
        bannerPic: "./CarDetails/JaguarF-type/JaguarF-type.jpg",
        detailPic: ["./CarDetails/JaguarF-type/p1.jpg","./CarDetails/JaguarF-type/p2.jpg","./CarDetails/JaguarF-type/p3.jpg","./CarDetails/JaguarF-type/p4.jpg","./CarDetails/JaguarF-type/p5.jpg","./CarDetails/JaguarF-type/p6.jpg","./CarDetails/JaguarF-type/p7.jpg","./CarDetails/JaguarF-type/p8.jpg",],
    },
    {
        id:20,
        name: "2017 Nissan GT-R",
        brand: "Nissan",
        model: "GT-R",
        color: "orange",
        year: 2017,
        mileage: 3200,
        price: 100000,
        bodyType: "Coupe",
        doors: 2,
        engine: "3.8L V6, Twin Turbo",
        transmission: " 6-speed dual-clutch automatic",
        fuel: "Gasoline",
        driveTrain: "All Wheel Drive (AWD)",
        bannerPic: "./CarDetails/NissanGTR/NissanGTR.jpg",
        detailPic: ["./CarDetails/NissanGTR/p1.jpg","./CarDetails/NissanGTR/p2.jpg","./CarDetails/NissanGTR/p3.jpg","./CarDetails/NissanGTR/p4.jpg","./CarDetails/NissanGTR/p5.jpg","./CarDetails/NissanGTR/p6.jpg","./CarDetails/NissanGTR/p7.jpg","./CarDetails/NissanGTR/p8.jpg","./CarDetails/NissanGTR/p9.jpg","./CarDetails/NissanGTR/p10.jpg","./CarDetails/NissanGTR/p11.jpg","./CarDetails/NissanGTR/p12.jpg",],
    },
]

export default data;